/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACESERVIDORPEDIDOSSERVIDORDISPLAY_H_RPCGEN
#define _INTERFACESERVIDORPEDIDOSSERVIDORDISPLAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXIDENTIFICACION2 20

struct nodo_hamburguesaActualizado {
	int cantidadIngredientesExtra;
	int tipoHamburguesa;
	char nombreHamburguesa[MAXIDENTIFICACION2];
};
typedef struct nodo_hamburguesaActualizado nodo_hamburguesaActualizado;

struct cocineroActualizado {
	int noCocinero;
	bool_t ocupado;
	nodo_hamburguesaActualizado objHamburguesaAPreparar;
};
typedef struct cocineroActualizado cocineroActualizado;

struct notificacion {
	cocineroActualizado cocineros[3];
	int cantidadUsuariosFilaVirtual;
};
typedef struct notificacion notificacion;

#define notificar_cocineros 0x20000002
#define notificar_cocineros_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define enviarNotificacion 1
extern  void * enviarnotificacion_1(notificacion *, CLIENT *);
extern  void * enviarnotificacion_1_svc(notificacion *, struct svc_req *);
extern int notificar_cocineros_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarNotificacion 1
extern  void * enviarnotificacion_1();
extern  void * enviarnotificacion_1_svc();
extern int notificar_cocineros_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_hamburguesaActualizado (XDR *, nodo_hamburguesaActualizado*);
extern  bool_t xdr_cocineroActualizado (XDR *, cocineroActualizado*);
extern  bool_t xdr_notificacion (XDR *, notificacion*);

#else /* K&R C */
extern bool_t xdr_nodo_hamburguesaActualizado ();
extern bool_t xdr_cocineroActualizado ();
extern bool_t xdr_notificacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACESERVIDORPEDIDOSSERVIDORDISPLAY_H_RPCGEN */
