/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "I_pedidos_display.h"
#include <time.h>
#include <stdbool.h>

/**
 * @brief Imprime por salida estandar la hora acutal
 */
void mostrarHoraUltimaActualizacion();

void *
enviarnotificacion_1_svc(notificacion *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("\n 				Pedidso asignados 			");
	printf("\n Cocinero		Tipo Hamburguesa	Cantidad Ingredientes				Nombres");
	for(int i = 0; i < 3; i++)
	{
		if(((*argp).cocineros[i].ocupado == true))
		{
			printf("\n  %d 				%d				%d 				%s",
			(*argp).cocineros[i].noCocinero, 
			(*argp).cocineros[i].objHamburguesaAPreparar.tipoHamburguesa, 
			(*argp).cocineros[i].objHamburguesaAPreparar.cantidadIngredientesExtra,
			(*argp).cocineros[i].objHamburguesaAPreparar.nombreHamburguesa);
		}
	}
	printf("\n Cantidad de pedidos en la fila:  %d", (*argp).cantidadUsuariosFilaVirtual);
	mostrarHoraUltimaActualizacion();
	printf("\n");	

	return (void *) &result;
}
void mostrarHoraUltimaActualizacion(){
	time_t tiempo_actual;
	struct tm *info_tiempo;

	//obtener el tiempo actual 
	time(&tiempo_actual);


	//Convertir el tiempo a una estructura local
	info_tiempo = localtime(&tiempo_actual);
	printf("\n Ultima actualizacion:  %02d: %02d\n",
	info_tiempo->tm_hour, //hora (0-23)
	info_tiempo->tm_min); //Minutos (0-59)
}
