/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "InterfaceClienteServidorPedidos.h"

bool_t
xdr_nodo_hamburguesa (XDR *xdrs, nodo_hamburguesa *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->cantidadIngredientesExtra))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tipoHamburguesa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombreHamburguesa, MAXIDENTIFICACION,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
