/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceServidorPedidosServidorDisplay.h"


void
notificar_cocineros_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char ipServidor[10];
	notificacion  objNotificacion;
	strcpy(ipServidor, "localhost");
#ifndef	DEBUG
	clnt = clnt_create (host, notificar_cocineros, notificar_cocineros_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	for(int i=0 ;i<3;i++){
		objNotificacion.cocineros[i].noCocinero=vectorCocinero[0].noCocinero;
		objNotificacion.cocineros[i].ocupado=vectorCocinero[0].ocupado;
		objNotificacion.cocineros[i].objHamburguesaAPreparar.cantidadIngredientesExtra = 
			vectorCocinero[0].objHamburguesaAPreparar.cantidadIngredientesExtra;
		strcpy(objNotificacion.cocineros[i].objHamburguesaAPreparar.nombreHamburguesa,vectorCocinero[i].objHamburguesaAPreparar.nombreHamburguesa);
		objNotificacion.cocineros[i].objHamburguesaAPreparar.tipoHamburguesa = 
			vectorCocinero[i].objHamburguesaAPreparar.tipoHamburguesa;
	}

	objNotificacion.cantidadUsuariosFilaVirtual=

	result_1 = enviarnotificacion_1(&objNotificacion, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	notificar_cocineros_1 (host);
exit (0);
}
