/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "InterfaceServidorPedidosServidorDisplay.h"

bool_t
xdr_nodo_hamburguesaActualizado (XDR *xdrs, nodo_hamburguesaActualizado *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->cantidadIngredientesExtra))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tipoHamburguesa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombreHamburguesa, MAXIDENTIFICACION2,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cocineroActualizado (XDR *xdrs, cocineroActualizado *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->noCocinero))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->ocupado))
		 return FALSE;
	 if (!xdr_nodo_hamburguesaActualizado (xdrs, &objp->objHamburguesaAPreparar))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_notificacion (XDR *xdrs, notificacion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cocineros, 3,
		sizeof (cocineroActualizado), (xdrproc_t) xdr_cocineroActualizado))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadUsuariosFilaVirtual))
		 return FALSE;
	return TRUE;
}
