/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceClienteServidorPedidos.h"
#include "InterfaceServidorPedidosServidorDisplay.h"
#include <stdbool.h>


int cantidadUsuariosFila=0;
nodo_hamburguesa filaVirtual[10];
void notificar_cocineros_1();
cocinero vectorCocineros[3];
int consultarNumeroCocineroDisponible() {
	int posicion=-1;
	for(int i = 0; i <3;i++){
		if(vectorCocineros[i].ocupado == false){
			posicion=i;
			break;
		}
	}
	return posicion;
}

int * generarturno_1_svc(nodo_hamburguesa *argp, struct svc_req *rqstp)
{
	static int result;
	int posicion = consultarNumeroCocineroDisponible();

	printf("\n");
	printf(" Hambruguesa a preparar\n");
	printf(" Nombre hamburguesa: %s\n", (*argp).nombreHamburguesa);
	printf(" Tipo de hamburguesa: %d\n", (*argp).tipoHamburguesa);
	printf(" Cantidad de ingreidientes extra: %d\n", (*argp).cantidadIngredientesExtra);

	if(posicion==-1){
		printf(" Los cocineros se encuentran ocupados\n");
		filaVirtual[cantidadUsuariosFila]=*argp;
		cantidadUsuariosFila++;
		printf(" La hambruguesa se agrego a la fila virtual\n");
	}else {
		printf(" El cocinero en la posicion %d esta libre y se asginara a la hambrugeusa con nombre %s\n", (posicion+1), (*argp).nombreHamburguesa);
		vectorCocineros[posicion].ocupado=true;
		vectorCocineros[posicion].objHamburguesaAPreparar=*argp;
	}
	result = cantidadUsuariosFila;
	notificar_cocineros_1();
	printf("\n");
	return &result;
}

void
notificar_cocineros_1()
{
	CLIENT *clnt;
	void  *result_1;
	char ipServidor[10];
	notificacion  objNotificacion;
	strcpy(ipServidor, "localhost");
#ifndef	DEBUG
	clnt = clnt_create (ipServidor, notificar_cocineros, notificar_cocineros_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (ipServidor);
		exit (1);
	}
#endif	/* DEBUG */

	for(int i=0 ;i<3;i++){
		objNotificacion.cocineros[i].noCocinero=vectorCocineros[i].noCocinero;
		objNotificacion.cocineros[i].ocupado=vectorCocineros[i].ocupado;
		objNotificacion.cocineros[i].objHamburguesaAPreparar.cantidadIngredientesExtra = 
			vectorCocineros[i].objHamburguesaAPreparar.cantidadIngredientesExtra;
		strcpy(objNotificacion.cocineros[i].objHamburguesaAPreparar.nombreHamburguesa,vectorCocineros[i].objHamburguesaAPreparar.nombreHamburguesa);
		objNotificacion.cocineros[i].objHamburguesaAPreparar.tipoHamburguesa = 
			vectorCocineros[i].objHamburguesaAPreparar.tipoHamburguesa;
	}

	objNotificacion.cantidadUsuariosFilaVirtual=cantidadUsuariosFila;

	result_1 = enviarnotificacion_1(&objNotificacion, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
