/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "I_coc_pedidos.h"


void
autorizar_cocineros_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  seleccionaridcocinero_1_arg;
	int  *result_2;
	int  terminarpedido_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, autorizar_cocineros, autorizar_cocineros_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = seleccionaridcocinero_1(&seleccionaridcocinero_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = terminarpedido_1(&terminarpedido_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];


	autorizar_cocineros_1 (host);
	
exit (0);
}
